const markets=[
{name:'Byte Club',symbol:'BYTE',creator:'bytebuilder',color:'#d7fa52',source:'TurboPad',price:'0.000842',change:46.1,volume:'4.82M',cap:'842K',score:94,progress:84,age:12,kind:'meme'},
{name:'Robin Pup',symbol:'RPUP',creator:'pupclub',color:'#b2d1c7',source:'Pons',price:'0.00318',change:28.7,volume:'3.11M',cap:'3.18M',score:91,progress:67,age:28,kind:'meme'},
{name:'Just Send It',symbol:'SEND',creator:'sendstudio',color:'#e6b97b',source:'TurboPad',price:'0.00195',change:19.3,volume:'2.47M',cap:'1.95M',score:89,progress:92,age:54,kind:'meme'},
{name:'Glitch Goblin',symbol:'GLITCH',creator:'glitchmaker',color:'#aaa0da',source:'PEEPS',price:'0.000618',change:-4.7,volume:'1.94M',cap:'618K',score:83,progress:58,age:8,kind:'meme'},
{name:'Orbit Society',symbol:'ORBIT',creator:'orbitcollective',color:'#9daeda',source:'Pons',price:'0.000392',change:12.8,volume:'864K',cap:'392K',score:80,progress:43,age:5,kind:'meme'},
{name:'Gold Reserve',symbol:'GOLDx',creator:'Example issuer',color:'#d9cc9a',source:'RWA',price:'2,641.82',change:.42,volume:'1.22M',cap:'8.4M',score:null,progress:100,age:90,kind:'rwa'},
{name:'Treasury Vault',symbol:'USTB',creator:'Example issuer',color:'#a4c4a2',source:'RWA',price:'1.003',change:.03,volume:'382K',cap:'2.1M',score:null,progress:100,age:90,kind:'rwa'},
{name:'Equity Index',symbol:'EQX',creator:'Example issuer',color:'#a5c3d0',source:'RWA',price:'74.23',change:1.81,volume:'641K',cap:'1.9M',score:null,progress:100,age:90,kind:'rwa'}];

const $=selector=>document.querySelector(selector),dialog=$('#dialog'),storageKey='turbopad.watchlist.v1';
const state={view:'Explore',filter:'All',query:'',source:'All launchpads',layout:'list',saved:loadSaved()};
function loadSaved(){try{return new Set(JSON.parse(localStorage.getItem(storageKey)||'[]').filter(Number.isInteger))}catch{return new Set()}}
function saveWatchlist(){localStorage.setItem(storageKey,JSON.stringify([...state.saved]))}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function chart(seed,down=false){let y=63;const points=Array.from({length:33},(_,i)=>{y=Math.max(8,Math.min(85,y+Math.sin(i*2.7+seed)*12+(down?.5:-1.25)));return `${i*10},${y.toFixed(1)}`}).join(' '),color=down?'#dc9e90':'#d9af79';return `<svg viewBox="0 0 320 96" preserveAspectRatio="none" role="img" aria-label="Illustrative price trend"><path d="M0 30H320M0 65H320" stroke="#4a4238" stroke-dasharray="3 5"/><polygon points="0,96 ${points} 320,96" fill="${color}" opacity=".055"/><polyline points="${points}" fill="none" stroke="${color}" stroke-width="1.7" vector-effect="non-scaling-stroke"/></svg>`}
function getVisibleMarkets(){const query=state.query.trim().toLowerCase();return markets.filter((market,index)=>{const matchesQuery=!query||`${market.name} ${market.symbol} ${market.creator}`.toLowerCase().includes(query),matchesSource=state.source==='All launchpads'||market.source===state.source,matchesView=state.view==='RWA Markets'?market.kind==='rwa':state.view==='Turbo Radar'?market.score!==null:state.view==='Watchlist'?state.saved.has(index):true,matchesFilter=state.filter==='Trending'?market.change>10:state.filter==='New'?market.age<=15:state.filter==='Graduating'?market.kind==='meme'&&market.progress>=80:true;return matchesQuery&&matchesSource&&matchesView&&matchesFilter}).sort((a,b)=>state.view==='Turbo Radar'?(b.score||0)-(a.score||0):0)}
function card(market){const index=markets.indexOf(market),saved=state.saved.has(index),name=escapeHtml(market.name),symbol=escapeHtml(market.symbol);return `<article class="market-card"><div class="card-head"><div class="avatar" style="--avatar:${market.color}">${symbol[0]}</div><div class="token-info"><h3>${name}</h3><span>$${symbol} · ${market.kind==='rwa'?'Concept asset':`${market.age}m ago`}</span></div><button class="save ${saved?'saved':''}" data-save="${index}" aria-label="${saved?'Remove':'Add'} ${name} ${saved?'from':'to'} watchlist" aria-pressed="${saved}">${saved?'★':'☆'}</button></div><div class="card-price"><strong>$${market.price}</strong><span class="change ${market.change<0?'negative':''}">${market.change>0?'↗ +':'↘ '}${market.change}%</span></div><div class="chart">${chart(index+1,market.change<0)}</div><div class="card-metrics"><div><span>24H VOLUME</span><b>$${market.volume}</b></div><div><span>MARKET CAP</span><b>$${market.cap}</b></div><div><span>${market.kind==='rwa'?'ATTESTATION':'TURBO SCORE'}</span><b class="score-badge">${market.score?`ϟ ${market.score}`:'Not verified'}</b></div></div><div class="progress-caption"><span>${market.kind==='rwa'?'Issuer review required':'Bonding curve'}</span><span>${market.kind==='rwa'?'Concept':`${market.progress}%`}</span></div><div class="progress"><i style="width:${market.kind==='rwa'?0:market.progress}%"></i></div><div class="card-bottom"><span class="source-tag">◈ ${escapeHtml(market.source)}</span><button class="detail-button" data-detail="${index}">View market ↗</button></div></article>`}
function updateChrome(){const copy={Explore:{title:'Your next move.<br><em>Starts here.</em>',subtitle:'Discover momentum.<br>Launch your community.',section:'Discover markets'},'Turbo Radar':{title:'Signal before the crowd.',subtitle:'Track momentum, liquidity and wallet concentration.',section:'Radar signals'},'Meme Battles':{title:'Community discovery.',subtitle:'A place in the spotlight.',section:'Discover markets'},'RWA Markets':{title:'Markets with context.',subtitle:'Explore asset concepts with issuer context.',section:'Real-world asset concepts'},'Creator Studio':{title:'Creator Studio.',subtitle:'Understand the economics behind your next launch.',section:'Creator tools'},Watchlist:{title:'Your next move.',subtitle:'Your saved markets, ready when you are.',section:'Saved markets'}}[state.view];$('#crumb').textContent=state.view;$('#title').innerHTML=copy.title;$('#subtitle').innerHTML=copy.subtitle;$('#sectionTitle').textContent=copy.section;$('#savedCount').textContent=state.saved.size;document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===state.view));document.querySelectorAll('[data-filter]').forEach(button=>button.classList.toggle('active',button.dataset.filter===state.filter));$('.controls').hidden=state.view==='Creator Studio';$('#resultCount').hidden=state.view==='Creator Studio'}
function renderStudio(){$('#studio').innerHTML='<div class="studio-panel"><span class="eyebrow">CREATOR REVENUE / SIMULATOR</span><h3>Build a community.<br>Share in its activity.</h3><p class="dialog-copy">Illustrative allocation: a 1% trading fee, with 50% of that fee assigned to the creator.</p><label for="volume">Trading volume in USD</label><input class="revenue-input" type="number" id="volume" value="100000" min="0" step="1000"><div class="revenue-result" id="revenue">$500.00</div><span class="muted">Estimated creator revenue · not a payout</span><div class="allocations"><i></i><i></i><i></i></div><p class="dialog-copy">50% Creator · 30% Protocol · 20% Ecosystem</p><button class="lime" data-launch>Preview a token launch ↗</button></div>'}
function render(){updateChrome();const visible=getVisibleMarkets();$('#cards').innerHTML=visible.map(card).join('')||'<div class="empty">No markets match these filters.<br>Try another filter or broaden your search.</div>';$('#resultCount').textContent=`${visible.length} ${visible.length===1?'market':'markets'}`;$('#studio').hidden=state.view!=='Creator Studio';if(state.view==='Creator Studio')renderStudio();document.dispatchEvent(new CustomEvent('turbopad:render',{detail:{state,markets:visible}}))}
function setView(nextView){state.view=nextView;state.filter='All';state.query='';state.source='All launchpads';$('#search').value='';$('#source').value='All launchpads';render();if(nextView==='Meme Battles')battle()}
function open(content){$('#dialogContent').innerHTML=content;if(!dialog.open)dialog.showModal()}
function detail(index){const market=markets[index];if(!market)return;const saved=state.saved.has(index);open(`<div class="token-heading"><div class="avatar" style="--avatar:${market.color}">${escapeHtml(market.symbol)[0]}</div><div><h2>${escapeHtml(market.name)}</h2><span>$${escapeHtml(market.symbol)} · ${escapeHtml(market.source)}</span></div></div><div class="card-price"><strong>$${market.price}</strong><span class="change">Illustrative price</span></div><div class="chart">${chart(index+1,market.change<0)}</div><p class="dialog-copy">${market.kind==='rwa'?'Concept only. Issuer, collateral, redemption terms and investor eligibility require verification before an asset could be listed.':'Illustrative market data. Turbo Score summarizes activity; it does not predict returns or certify token safety.'}</p><div class="score-list"><div class="score-line"><span>24h volume</span><b>$${market.volume}</b></div><div class="score-line"><span>${market.kind==='rwa'?'Issuer attestation':'Turbo Score'}</span><b>${market.score??'Not verified'}</b></div><div class="score-line"><span>Contract verification</span><b>Not connected</b></div></div><button class="outline full" data-save="${index}">${saved?'Remove from':'Add to'} watchlist</button><button class="lime full" id="demoTrade">Preview trade</button>`)}
function toast(message){const element=$('#toast');element.textContent=message;element.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>element.classList.remove('show'),2600)}
function toggleSaved(index){state.saved.has(index)?state.saved.delete(index):state.saved.add(index);saveWatchlist();render();toast(state.saved.has(index)?'Added to your watchlist':'Removed from your watchlist');if(dialog.open)detail(index)}
function launch(){open('<h2>Your next launch starts here.</h2><p class="dialog-copy">Create a local preview. No token or blockchain transaction will be created.</p><form id="launchForm"><label for="tokenName">Token name</label><input id="tokenName" required maxlength="40" placeholder="Turbo Cat"><label for="ticker">Ticker</label><input id="ticker" required maxlength="10" pattern="[A-Za-z0-9]+" placeholder="TCAT"><label for="launchMode">Launch mode</label><select id="launchMode"><option>Turbo · discovery boost concept</option><option>Standard · bonding curve concept</option></select><button class="lime full" type="submit">Create launch preview ↗</button></form>')}
function battle(){open('<h2>Choose your community.</h2><p class="dialog-copy">Try a demo vote. The winning community receives discovery exposure in this concept, not financial rewards.</p><div class="fight"><div><div class="avatar lime-avatar">B</div><b>$BYTE</b></div><span>VS</span><div><div class="avatar purple-avatar">G</div><b>$GLITCH</b></div></div><button class="lime full" data-vote="BYTE">Support $BYTE</button><button class="outline full" data-vote="GLITCH">Support $GLITCH</button>')}
window.TurboPad={markets,state,getVisibleMarkets,chart,detail,render,setView};
document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;if(button.dataset.view)setView(button.dataset.view);if(button.dataset.filter){state.filter=button.dataset.filter;render()}if('save'in button.dataset)toggleSaved(Number(button.dataset.save));if('detail'in button.dataset)detail(Number(button.dataset.detail));if('launch'in button.dataset)launch();if(button.dataset.vote){const byte=button.dataset.vote==='BYTE';$('#battleFill').style.width=byte?'65%':'63%';$('#battleLeft').textContent=byte?'65%':'63%';$('#battleRight').textContent=byte?'35%':'37%';dialog.close();toast(`Demo vote recorded for $${button.dataset.vote}`)}if(button.id==='demoTrade')open('<h2>Trading preview</h2><p class="dialog-copy">Wallet and market contracts are not connected. This UI does not submit orders or use real funds.</p><button class="lime full" id="closeTrade">Back to markets</button>');if(button.id==='closeTrade')dialog.close()});
document.querySelector('.brand-refined').addEventListener('click',event=>{event.preventDefault();setView('Explore')});
$('#close').onclick=()=>dialog.close();dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});$('#search').addEventListener('input',event=>{state.query=event.target.value;render()});$('#source').addEventListener('change',event=>{state.source=event.target.value;render()});$('#radarMore').onclick=()=>setView('Turbo Radar');$('#battleOpen').onclick=battle;$('#wallet').onclick=()=>open('<h2>Wallet preview</h2><p class="dialog-copy">This is an interactive UI prototype. Wallet connectivity is not implemented, and no wallet address is being requested.</p><button class="lime full" id="closeTrade">Continue exploring</button>');$('#scoreHelp').onclick=()=>open('<h2>Momentum, with context.</h2><p class="dialog-copy">Proposed Turbo Score weights. Values on this prototype are sample scores and are not calculated from live data.</p><div class="score-list">'+[['Volume quality','25%'],['Unique buyers','25%'],['Holder growth','20%'],['Liquidity progress','15%'],['Wallet distribution','15%']].map(([label,weight])=>`<div class="score-line"><span>${label}</span><b>${weight}</b></div>`).join('')+'</div><p class="dialog-copy">RWA concepts are evaluated through issuer and collateral checks, not meme momentum scoring.</p>');document.addEventListener('input',event=>{if(event.target.id==='volume')$('#revenue').textContent=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Math.max(0,Number(event.target.value)||0)*.005)});document.addEventListener('submit',event=>{if(event.target.id==='launchForm'){event.preventDefault();const name=$('#tokenName').value.trim();dialog.close();toast(`Launch preview prepared for ${name} · no token created`)}});$('#radarGraph').innerHTML=chart(8);render();
