(() => {
  const table=document.getElementById('marketTable'),cards=document.getElementById('cards'),overview=document.getElementById('marketOverview'),displayOptions=document.querySelector('.display-options');
  let selectedPeriod='24H';
  function renderSpotlight(period){const seed={'1H':3,'24H':8,'7D':14}[period],points=Array.from({length:65},(_,index)=>[index*10,Math.max(16,166-index*1.8+Math.sin(index*1.9+seed)*8+Math.cos(index*.6+seed)*15)]),path=points.map(point=>point.join(',')).join(' '),bars=points.map((_,index)=>`<rect x="${index*10}" y="${220-(8+Math.abs(Math.sin(index+seed))*20)}" width="5" height="${8+Math.abs(Math.sin(index+seed))*20}" fill="#d9af79" opacity=".13"/>`).join('');document.getElementById('spotlightChart').innerHTML=`<svg viewBox="0 0 640 222" preserveAspectRatio="none" role="img" aria-label="Illustrative ${period} price chart for Byte Club"><defs><linearGradient id="spotlightArea" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#d9af79" stop-opacity=".2"/><stop offset="1" stop-color="#d9af79" stop-opacity="0"/></linearGradient></defs><path d="M0 35H640M0 85H640M0 135H640M0 185H640" stroke="#ffffff0c" stroke-dasharray="2 6"/><polygon points="0,222 ${path} 640,222" fill="url(#spotlightArea)"/>${bars}<polyline points="${path}" fill="none" stroke="#d9af79" stroke-width="2" vector-effect="non-scaling-stroke"/><circle cx="640" cy="${points.at(-1)[1]}" r="4" fill="#ecd2ad"/></svg>`;const ticks={'1H':['00m','15m','30m','45m','60m'],'24H':['00:00','06:00','12:00','18:00','24:00'],'7D':['Mon','Tue','Thu','Sat','Sun']}[period];document.getElementById('chartAxis').innerHTML=ticks.map(label=>`<span>${label}</span>`).join('')}
  function sparkline(index,negative){const path=Array.from({length:17},(_,step)=>`${step*6},${Math.max(3,Math.min(33,25-step*(negative?-.25:.95)+Math.sin(step*2+index)*6))}`).join(' ');return `<svg viewBox="0 0 96 36" aria-hidden="true"><polyline points="${path}" fill="none" stroke="${negative?'#dc9e90':'#d3ad7b'}" stroke-width="1.5"/></svg>`}
  function renderTable(visibleMarkets){if(!visibleMarkets.length){table.innerHTML='<div class="empty">No markets match these filters.</div>';return}table.innerHTML=`<table class="market-table"><thead><tr><th>Market</th><th>Price</th><th>24h change</th><th>Volume</th><th>7-point trend</th><th>Score</th><th><span class="sr-only">Details</span></th></tr></thead><tbody>${visibleMarkets.map((market,rank)=>{const index=window.TurboPad.markets.indexOf(market);return `<tr><td><div class="table-token"><span class="rank">${String(rank+1).padStart(2,'0')}</span><div class="avatar" style="--avatar:${market.color}">${market.symbol[0]}</div><div><b>${market.name}</b><small>${market.symbol} <span>· ${market.source}</span></small></div></div></td><td>$${market.price}</td><td class="${market.change<0?'negative':'up'}">${market.change>0?'+':''}${market.change}%</td><td>$${market.volume}</td><td><div class="table-spark">${sparkline(index,market.change<0)}</div></td><td><span class="table-score">${market.score?`ϟ ${market.score}`:'RWA'}</span></td><td><button data-detail="${index}" aria-label="View ${market.name}">↗</button></td></tr>`}).join('')}</tbody></table>`}
  function sync({detail}){const studio=detail.state.view==='Creator Studio';overview.hidden=detail.state.view!=='Explore';displayOptions.hidden=studio;table.hidden=studio||detail.state.layout==='grid';cards.hidden=studio||detail.state.layout!=='grid';if(!studio&&detail.state.layout==='list')renderTable(detail.markets)}
  function setLayout(layout){window.TurboPad.state.layout=layout;[['listView','list'],['gridView','grid']].forEach(([id,value])=>{const selected=value===layout,button=document.getElementById(id);button.classList.toggle('selected',selected);button.setAttribute('aria-pressed',String(selected))});window.TurboPad.render()}
  document.getElementById('listView').onclick=()=>setLayout('list');document.getElementById('gridView').onclick=()=>setLayout('grid');document.getElementById('chartRanges').onclick=event=>{const button=event.target.closest('[data-period]');if(!button)return;selectedPeriod=button.dataset.period;document.querySelectorAll('[data-period]').forEach(item=>{const selected=item===button;item.classList.toggle('selected',selected);item.setAttribute('aria-pressed',String(selected))});renderSpotlight(selectedPeriod)};document.addEventListener('turbopad:render',sync);renderSpotlight(selectedPeriod);sync({detail:{state:window.TurboPad.state,markets:window.TurboPad.getVisibleMarkets()}});
})();
