/* Compile contracts/TurboToken.sol → Web/dist/token-artifact.js
   (embedded as window.TurboTokenArtifact so the static site needs no build). */
import { readFileSync, writeFileSync } from 'node:fs';
import solc from 'solc';

const source = readFileSync('contracts/TurboToken.sol', 'utf8');
const input = {
  language: 'Solidity',
  sources: { 'TurboToken.sol': { content: source } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object'] } },
  },
};

const output = JSON.parse(solc.compile(JSON.stringify(input)));
const errors = (output.errors || []).filter(e => e.severity === 'error');
if (errors.length) {
  console.error(errors.map(e => e.formattedMessage).join('\n'));
  process.exit(1);
}

const contract = output.contracts['TurboToken.sol'].TurboToken;
const artifact = { abi: contract.abi, bytecode: contract.evm.bytecode.object };
if (!artifact.bytecode || artifact.bytecode.includes('_')) {
  console.error('Bytecode missing or has unresolved link placeholders');
  process.exit(1);
}

const banner = '/* GENERATED by scripts/compile-token.mjs — do not edit by hand. */\n';
writeFileSync('Web/dist/token-artifact.js', `${banner}window.TurboTokenArtifact = ${JSON.stringify(artifact)};\n`);
writeFileSync('contracts/TurboToken.artifact.json', JSON.stringify(artifact, null, 2));

/* The Next.js app consumes the same artifact as a typed module. Emitting it
   here keeps both front-ends on one compile, so recompiling the contract can
   never leave the two builds deploying different bytecode. */
const tsBanner = `/* GENERATED from contracts/TurboToken.sol by scripts/compile-token.mjs — do not edit by hand.
   Kept as a .ts module rather than JSON so it needs no import attributes and
   resolves identically under Node's type stripping and the Next.js bundler. */\n\n`;
writeFileSync(
  'web-next/lib/token-artifact.ts',
  tsBanner
  + `export const TOKEN_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n`
  + '/** Creation bytecode, no 0x prefix. */\n'
  + `export const TOKEN_BYTECODE = '${artifact.bytecode}';\n\n`
  + 'const artifact = { abi: TOKEN_ABI, bytecode: TOKEN_BYTECODE };\nexport default artifact;\n',
);

console.log(`OK — bytecode ${artifact.bytecode.length / 2} bytes, ABI ${artifact.abi.length} entries`);
console.log('wrote Web/dist/token-artifact.js, contracts/TurboToken.artifact.json, web-next/lib/token-artifact.ts');
