/* Compile contracts/TurboToken.sol → Web/dist/token-artifact.js
   (embedded as window.TurboTokenArtifact so the static site needs no build). */
import { readFileSync, writeFileSync } from 'node:fs';
import solc from 'solc';

const source = readFileSync('contracts/TurboToken.sol', 'utf8');
const input = {
  language: 'Solidity',
  sources: { 'TurboToken.sol': { content: source } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object'] } },
  },
};

const output = JSON.parse(solc.compile(JSON.stringify(input)));
const errors = (output.errors || []).filter(e => e.severity === 'error');
if (errors.length) {
  console.error(errors.map(e => e.formattedMessage).join('\n'));
  process.exit(1);
}

const contract = output.contracts['TurboToken.sol'].TurboToken;
const artifact = { abi: contract.abi, bytecode: contract.evm.bytecode.object };
if (!artifact.bytecode || artifact.bytecode.includes('_')) {
  console.error('Bytecode missing or has unresolved link placeholders');
  process.exit(1);
}

const banner = '/* GENERATED by scripts/compile-token.mjs — do not edit by hand. */\n';
writeFileSync('Web/dist/token-artifact.js', `${banner}window.TurboTokenArtifact = ${JSON.stringify(artifact)};\n`);
writeFileSync('contracts/TurboToken.artifact.json', JSON.stringify(artifact, null, 2));
console.log(`OK — bytecode ${artifact.bytecode.length / 2} bytes, ABI ${artifact.abi.length} entries`);
